version: '3.2'

services:
    traefik:
        container_name: traefik
        image: traefik:1.6.4
        command: --api --docker --docker.swarmMode --docker.watch --docker.domain=service.jsoude.net --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0"
        expose:
          - 80
          - 443
        ports:
          - mode: host
            published: 80
            target: 80
          - mode: host
            published: 443
            target: 443        
          - mode: host
            published: 8080
            target: 8080
        networks:
          - service
        deploy:
          mode: global
          placement:
            constraints:
              - node.role == manager
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./config/acme.json:/etc/traefik/acme.json
          - ./config/traefik.toml:/etc/traefik/traefik.toml

networks:
    service:
        external:
            name: swarm-service 

