version: '3'

services:
  reverse-proxy:
    image: traefik #The official Traefik docker image
    command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    containe_name: traefik
    labels:
      - "traefik.frontend.rule=Host:traefik.${MYDOMAIN}"
    networks:
      - service
    ports:
      - "80:80"     #The HTTP port
      - "443:443"     #The HTTP port
      - "8080:8080" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
      - ./config/traefik.toml:/etc/traefik/traefik.toml
      - ./config/acme.json:/etc/traefik/acme.json

networks:
  service:
    external:
      name: service

